on:
  push:
    branches: master
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    # - run: |
    #     mkdir -p .platform/nginx/conf.d
    #     echo "client_max_body_size 100M;" > .platform/nginx/conf.d/myconfig.conf
    # - run: zip -b src -r src.zip *
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - run: dotnet publish src -o publish -c Release -r win-x64
    - uses: actions/upload-artifact@v2
      with:
        path: publish
    # - uses: gojanpaolo/webdeploy-action@master
    #   with:
    #     webSiteName: test-app
    #     package: ${{ format('{0}\dist', github.workspace) }}
    #     removeAdditionalFilesFlag: true
    #     takeAppOfflineFlag: true
    # - run: |
    #     & "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\ResGen.exe"
    # - uses: microsoft/variable-substitution@v1
    #   with:
    #     files: 'src/Gldd.PostDredge/appsettings.json'
    #   env:
    #     ConnectionStrings.PostDredge: ${{ secrets.connection_string }}
    # - run: |
    #     dotnet tool install --global dotnet-ef
    #     dotnet ef database update -p src/Gldd.PostDredge
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - uses: actions/download-artifact@v2
