on:
  push:
    branches: master
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    # - run: dotnet publish src -o dist -c Release -r win-x64
    # - uses: gojanpaolo/webdeploy-action@master
    #   with:
    #     webSiteName: test-app
    #     package: ${{ format('{0}\dist', github.workspace) }}
    #     removeAdditionalFilesFlag: true
    #     takeAppOfflineFlag: true
    # - run: |
    #     & "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\ResGen.exe"
    - uses: microsoft/variable-substitution@v1
      with:
        files: 'src/Gldd.PostDredge/appsettings.json'
      env:
        ConnectionStrings.PostDredge: ${{ secrets.connection_string }}
    - run: dotnet ef database update
