name: .NET Core
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: dotnet publish src -c Release -r win-x64
    - name: GitHub Actions WebDeploy
      uses: gojanpaolo/webdeploy-action@master
      with:
        webSiteName: 'test-app'
        package: ${{ format('{0}\actions-demo\src\Gldd.PostDredge\bin\Release\netcoreapp3.1\win-x64\publish', runner.workspace) }}
        takeAppOfflineFlag: ${{ true }}
